apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: system
data:
  config.yaml: |
    namespace:
      commonLabels:
        accurate.cybozu.com/template: init-template
      roleBindingTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: admin
        subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: Group
            name: {{ .Name }}
          - kind: ServiceAccount
            name: node-{{ .Name }}
            namespace: teleport
          {{- range .Roles.admin }}
          - apiGroup: rbac.authorization.k8s.io
            kind: Group
            name: {{ .Name }}
          - kind: ServiceAccount
            name: node-{{ .Name }}
            namespace: teleport
          {{- end }}
    argocd:
      namespace: argocd
      appProjectTemplate: |
        apiVersion: argoproj.io/v1alpha1
        kind: AppProject
        spec:
          destinations:
          {{- range .Namespaces }}
            - namespace: {{ . }}
              server: '*'
          {{- end }}
          namespaceResourceBlacklist:
            - group: ""
              kind: ResourceQuota
            - group: ""
              kind: LimitRange
          roles:
            - groups:
                - cybozu-go:{{with .ExtraParams.GitHubTeam}}{{ . }}{{else}}{{ .Name }}{{end}}
                {{- range .Roles.admin }}
                - cybozu-go:{{with .ExtraParams.GitHubTeam}}{{ . }}{{else}}{{ .Name }}{{end}}
                {{- end }}
              name: admin
              policies:
                - p, proj:{{ .Name }}:admin, applications, *, {{ .Name }}/*, allow
          sourceNamespaces:
            {{- range .Namespaces }}
            - {{ . }}
            {{- end }}
          sourceRepos:
            {{- range .Repositories }}
            - '{{ . }}'
            {{- else }}
            - '*'
            {{- end }}
      preventAppCreationInArgoCDNamespace: true
