apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cattage.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cattage.labels" . | nindent 4 }}
data:
  config.yaml: |
    namespace:
      {{- with .Values.controller.config.namespace.commonLabels }}
      commonLabels: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.config.namespace.commonAnntations }}
      commonAnnotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      roleBindingTemplate: {{ required ".Values.controller.config.namespace.roleBindingTemplate required!" .Values.controller.config.namespace.roleBindingTemplate | toYaml | nindent 8 }}
    argocd:
      namespace: {{ required ".Values.controller.config.argocd.namespace required!" .Values.controller.config.argocd.namespace }}
      appProjectTemplate: {{ required ".Values.controller.config.argocd.appProjectTemplate required!" .Values.controller.config.argocd.appProjectTemplate | toYaml | nindent 8 }}
      preventAppCreationInArgoCDNamespace: {{ required ".Values.controller.config.argocd.preventAppCreationInArgoCDNamespace required!" .Values.controller.config.argocd.preventAppCreationInArgoCDNamespace }} 
