# permissions for end users to view syncwindows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cattage
    app.kubernetes.io/managed-by: kustomize
  name: syncwindow-viewer-role
rules:
- apiGroups:
  - cattage.cybozu.io
  resources:
  - syncwindows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cattage.cybozu.io
  resources:
  - syncwindows/status
  verbs:
  - get
