name: "GoReleaser with Cosign"
description: "Install cosign and run goreleaser with the given args"

inputs:
  args:
    description: "Arguments to pass to goreleaser"
    required: true

runs:
  using: composite
  steps:
    - name: Install cosign for goreleaser
      uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
      with:
        version: v2.15.3
        args: ${{ inputs.args }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
