apiVersion: cattage.cybozu.io/v1beta1
kind: SyncWindow
metadata:
  labels:
    app.kubernetes.io/name: cattage
    app.kubernetes.io/managed-by: kustomize
  name: syncwindow-sample
  namespace: sub-1
spec:
  syncWindows:
  - kind: allow
    schedule: '10 1 * * *'
    duration: 1h
    applications:
    - '*-prod'
    manualSync: true
  - kind: deny
    schedule: '0 22 * * *'
    timeZone: "Europe/Amsterdam"
    duration: 1h
    namespaces:
    - default
  - kind: allow
    schedule: '0 23 * * *'
    duration: 1h
    clusters:
    - in-cluster
    - cluster1
