apiVersion: cattage.cybozu.io/v1beta1
kind: Tenant
metadata:
  name: a-team
spec:
  rootNamespaces:
    - name: app-a
  controllerName: second
  extraParams:
    GitHubTeam: a-team-gh
---
apiVersion: cattage.cybozu.io/v1beta1
kind: Tenant
metadata:
  name: b-team
spec:
  rootNamespaces:
    - name: app-b
  argocd:
    repositories:
      - "https://github.com/cybozu-go/*"
  delegates:
    - name: a-team
      roles:
        - admin
  extraParams:
    GitHubTeam: b-team-gh
