apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- includeCRDs: true
  name: argo-cd
  namespace: argocd
  releaseName: argocd
  repo: https://argoproj.github.io/argo-helm
  valuesFile: argocd-values.yaml
  version: 8.2.5
namespace: argocd
resources:
  - second-application-controller.yaml
patches:
  - path: argocd-patches.yaml
