name: "Setup tools"
description: "Setup tools with aqua"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@e15472de27e1608c42683369963554b2f0c65f19 # v４.0.0
      with:
        aqua_version: v2.53.7
        github_token: ${{ inputs.github_token }}
