name: "Setup tools"
description: "Setup tools with aqua"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@8df3d04fe8536da46ca80a1598e903ca8e2137d6 # v４.0.0
      with:
        aqua_version: v2.53.6
        github_token: ${{ inputs.github_token }}
